meta-isg: qat: fix inline build errors for gcc5
gcc5 has changed its default standard to gnu11 from gnu89.
These two standards have different inline semantics. This
results in errors like:

   undefined reference to `icp_adf_getQueueNext'
   undefined reference to `icp_adf_updateQueueTail'
   undefined reference to `icp_adf_pollQueue'
   undefined reference to `icp_adf_queueDataToSend'
   undefined reference to `icp_adf_getQueueMemory'

Use the -fgnu89-inline command line option as suggested in [1].

Also, make sure that all the CFLAGS values are being picked up
by the compiler.

[1]  https://gcc.gnu.org/gcc-5/porting_to.html

Signed-off-by: Anuj Mittal <anujx.mittal@intel.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
(cherry picked from commit 1201a576c9bcdab3bfcf87efeb2184f0025ae53e)
Signed-off-by: Saul Wold <sgw@linux.intel.com>