thermald: fix the url
The trailing slash on the github uri causes fetch failures. Ex:

    Cloning into bare repository '.../downloads/git2/github.com.intel.thermal_daemon.'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>