meta-intel: support distro without OpenGL
When a distro disables OpenGL or using meta-intel without any distro
set, a world build fails for all recipes depending directly or
indirectly on libva, because libva is disables unless opengl is in
DISTRO_FEATURES. "opengl" must be checked for in all those recipes.

The specific use case was testing of meta-intel with
yocto-compat-layer.py against just OE-core with the local.conf.sample
from OE-core, i.e. DISTRO unset. Without this change, that failed
with:

ERROR: Nothing PROVIDES 'libva' (but /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami-utils_1.1.0.bb, /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami_1.1.0.bb, /fast/work/meta-intel/common/recipes-multimedia/libva/libva-intel-driver_1.7.3.bb DEPENDS on or otherwise requires it)
ERROR: libva was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
ERROR: Nothing RPROVIDES 'libyami-dev' (but /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami_1.1.0.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libyami-dev'
NOTE: Runtime target 'libyami-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libyami-dev']
ERROR: Nothing RPROVIDES 'libva' (but /fast/work/meta-intel/common/recipes-multimedia/libva/va-intel.bb RDEPENDS on or otherwise requires it)
ERROR: libva was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
NOTE: Runtime target 'libva' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libva']
ERROR: Nothing RPROVIDES 'libva-intel-driver' (but /fast/work/meta-intel/common/recipes-multimedia/libva/libva-intel-driver_1.7.3.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libva-intel-driver'
NOTE: Runtime target 'libva-intel-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libva-intel-driver']
ERROR: Nothing RPROVIDES 'libyami-utils' (but /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami-utils_1.1.0.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libyami-utils'
NOTE: Runtime target 'libyami-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libyami-utils']
ERROR: Nothing RPROVIDES 'libyami-utils-dev' (but /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami-utils_1.1.0.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libyami-utils-dev'
NOTE: Runtime target 'libyami-utils-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libyami-utils-dev']
ERROR: Nothing RPROVIDES 'libyami' (but /fast/work/meta-intel/common/recipes-multimedia/libyami/libyami_1.1.0.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libyami'
NOTE: Runtime target 'libyami' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libyami']
ERROR: Nothing RPROVIDES 'libva-intel-driver-dev' (but /fast/work/meta-intel/common/recipes-multimedia/libva/libva-intel-driver_1.7.3.bb RDEPENDS on or otherwise requires it)
ERROR: No eligible RPROVIDERs exist for 'libva-intel-driver-dev'
NOTE: Runtime target 'libva-intel-driver-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libva-intel-driver-dev']

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>