meta-isg: qat: fix strict_str* compile errors
Defines strict_str* have become obsolete and removed entirely
starting from kernel v3.18. This results in errors like:

     error: implicit declaration of function 'strict_strtoull'
            [-Werror=implicit-function-declaration]

Replace strict_strtoull with kstrtoull to ensure qat 2.3.0-34
compiles.

Signed-off-by: Anuj Mittal <anujx.mittal@intel.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
(cherry picked from commit 88a5f5857d56e4a8952a7cd7d215178a78161871)
Signed-off-by: Saul Wold <sgw@linux.intel.com>