linux-yocto recipes: fix use of module_autoload_* vars
oecore/poky layer changed, needing replacement of all the module_autoload_*
recipe variables by the KERNEL_MODULE_AUTOLOAD variable.

This fixes these kind of buildtime errors coming from the meta-intel layer:

ERROR: KERNEL_MODULE_AUTOLOAD has replaced module_autoload_iwlwifi, please replace it!

Addresses bug:
[YOCTO #6460]

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>