intel_vaapi_driver.py: fix encoding pipeline
Add missing h264parse in pipeline

Error log:

dd Pipeline is PREROLLING ...
Got context from element 'vaapisink0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:qtdemux0: This file is corrupt and cannot be played.
Additional debug info:
../gst-plugins-good-1.18.2/gst/isomp4/qtdemux.c(12726): qtdemux_parse_trak (): /GstPipeline:pipeline0/GstQTDemux:qtdemux0
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:qtdemux0: This file contains no playable streams.

No need to export i965 driver anymore.

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>