linux-intel/5.10: update to v5.10.78
Update kernel config as well.

Backported patch to fix 32-bit compilation failure.

32-bit compilation failure log:

build/tmp/work-shared/intel-core2-32/kernel-source/include/linux/io-mapping.h:88:16: error: implicit declaration of function '__iomap_local_pfn_prot'; did you mean '__kmap_local_pfn_prot'? [-Werror=implicit-function-declaration]
|    88 |         return __iomap_local_pfn_prot(PHYS_PFN(phys_addr), mapping->prot);
|       |                ^~~~~~~~~~~~~~~~~~~~~~
|       |                __kmap_local_pfn_prot
| build/tmp/work-shared/intel-core2-32/kernel-source/include/linux/io-mapping.h:88:16: warning: returning 'int' from a function with return type 'void *' makes pointer from integer without a cast [-Wint-conversion]
|    88 |         return __iomap_local_pfn_prot(PHYS_PFN(phys_addr), mapping->prot);
|       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>