intel-graphics-compiler: fix compile issues
Backport patches to fix compile problems like:

| /build/build/tmp/work/corei7-64-poky-linux/intel-graphics-compiler/1.0.10395-r0/git/visa/LocalScheduler/SWSB_G4IR.cpp:1459:49: error: expected primary-expression before 'int'
|  1459 |         int maxTokenDelay = std::numeric_limits<int>::min(); //The delay may cause if reuse
|       |                                                 ^~~
| /build/build/tmp/work/corei7-64-poky-linux/intel-graphics-compiler/1.0.10395-r0/git/visa/LocalScheduler/SWSB_G4IR.cpp:1460:37: error: 'numeric_limits' is not a member of 'std'
|  1460 |         int minTokenDistance = std::numeric_limits<int>::max(); //The distance from the reused node

Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
(cherry picked from commit 311b43239440070f750a0ec44537a26c5f22e131)
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>